# Generated by Django 4.1.3 on 2023-01-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupAssistApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='userType',
            field=models.CharField(choices=[('Student', 'Student'), ('Department Head', 'Department Head'), ('Person-in-charge', 'Person-in-charge'), ('Teacher', 'Teacher'), ('Assistant Director for Academic Affairs', 'Assistant Director for Academic Affairs'), ('OAA Staff', 'OAA Staff')], max_length=255, null=True, verbose_name='userType'),
        ),
    ]
