# Generated by Django 4.1.2 on 2022-10-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupAssistApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERSGradeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('datetime', models.DateField()),
                ('ersfile', models.FileField(blank=True, upload_to='file')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='userType',
            field=models.CharField(choices=[('DH', 'Department Head'), ('Person-in-charge', 'Person-in-charge'), ('R', 'Registrar'), ('STDNT', 'Student')], max_length=255, null=True, verbose_name='userType'),
        ),
    ]
