# Generated by Django 4.1.2 on 2023-01-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TupAssistApp', '0002_remove_transferringreq_subj_teacher_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='studID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
